In [1]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
b = np.zeros((3, 4), dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
b.ndim

2

In [10]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
# we only have zeros & ones in numpy to create other matrix like for 2 or 3
# we have to do the following:
np.array([[2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [27]:
arr = np.ones((4, 2), dtype=int)
a = arr / 5
a

array([[0.2, 0.2],
       [0.2, 0.2],
       [0.2, 0.2],
       [0.2, 0.2]])

In [ ]:
np.eye(4, dtype=int) # Indentity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
np.empty((3, 4), dtype=int)

array([[      1631617098648,                  64,                   0,
                          0],
       [8214565720323784704, 3978703110874031153, 7005684804211795001,
        7292228735681847909],
       [3919313880096203571, 7292511301532792163, 7003435195650421808,
        3546131936242250033]])

In [34]:
import random
random.choice([1, 2, 3])

3

In [35]:
random.randrange(1, 100)

14

In [ ]:
random.random() # Between 0 (Included) & 1 (Excluded)

0.11853542104023707

In [40]:
lis = [1, 2, 3, 4, 5]
random.shuffle(lis)
lis

[1, 5, 4, 3, 2]

In [43]:
random.uniform(1, 3)

1.2702594657562412

In [44]:
# random number in numpy
np.array([])

array([], dtype=float64)

In [48]:
np.random.random_sample((5, 5))

array([[0.37702792, 0.36022223, 0.81964291, 0.57958054, 0.74362389],
       [0.36384242, 0.82172138, 0.85198956, 0.52857549, 0.04384718],
       [0.08965347, 0.41454865, 0.63306633, 0.75783229, 0.51225449],
       [0.77298711, 0.33736537, 0.52873257, 0.89799161, 0.27091999],
       [0.75339941, 0.79382987, 0.2856516 , 0.82835513, 0.66847281]])

In [53]:
np.random.rand(4, 2)

array([[0.89785151, 0.07919847],
       [0.67994679, 0.47884615],
       [0.15315839, 0.3051873 ],
       [0.88246952, 0.7376239 ]])

In [55]:
np.random.randn()

2.1290543292986195

In [57]:
arr1 = np.zeros((2, 4), dtype=int)
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
arr1[arr1 > -1]

array([0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
arr = np.fromfunction(lambda i, j: i == j, (4,4))

In [7]:
arr.ndim

2

In [8]:
arr.shape

(4, 4)

In [9]:
arr.size

16

In [11]:
np.array(list((i for i in range(5))))

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [16]:
np.linspace(1, 5, 100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [20]:
np.zeros((3, 3, 3), dtype=int).ndim

3

In [21]:
a = np.zeros((3, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
a.reshape(1, -1000000000)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
arr = np.random.randint(1, 10, (5, 6))
arr

array([[6, 8, 5, 7, 8, 3],
       [9, 3, 2, 8, 3, 3],
       [4, 9, 7, 3, 2, 9],
       [1, 1, 5, 9, 8, 2],
       [6, 5, 8, 4, 2, 6]], dtype=int32)

In [30]:
arr.reshape(3, -1)

array([[6, 8, 5, 7, 8, 3, 9, 3, 2, 8],
       [3, 3, 4, 9, 7, 3, 2, 9, 1, 1],
       [5, 9, 8, 2, 6, 5, 8, 4, 2, 6]], dtype=int32)

In [31]:
arr[1:4, 1:4]

array([[3, 2, 8],
       [9, 7, 3],
       [1, 5, 9]], dtype=int32)

In [32]:
arr.flatten()

array([6, 8, 5, 7, 8, 3, 9, 3, 2, 8, 3, 3, 4, 9, 7, 3, 2, 9, 1, 1, 5, 9,
       8, 2, 6, 5, 8, 4, 2, 6], dtype=int32)