In [2]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
b = np.zeros((3, 4), dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
b.ndim

2

In [10]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
# we only have zeros & ones in numpy to create other matrix like for 2 or 3
# we have to do the following:
np.array([[2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [27]:
arr = np.ones((4, 2), dtype=int)
a = arr / 5
a

array([[0.2, 0.2],
       [0.2, 0.2],
       [0.2, 0.2],
       [0.2, 0.2]])

In [ ]:
np.eye(4, dtype=int) # Indentity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
np.empty((3, 4), dtype=int)

array([[      1631617098648,                  64,                   0,
                          0],
       [8214565720323784704, 3978703110874031153, 7005684804211795001,
        7292228735681847909],
       [3919313880096203571, 7292511301532792163, 7003435195650421808,
        3546131936242250033]])

In [34]:
import random
random.choice([1, 2, 3])

3

In [35]:
random.randrange(1, 100)

14

In [ ]:
random.random() # Between 0 (Included) & 1 (Excluded)

0.11853542104023707

In [40]:
lis = [1, 2, 3, 4, 5]
random.shuffle(lis)
lis

[1, 5, 4, 3, 2]

In [43]:
random.uniform(1, 3)

1.2702594657562412

In [44]:
# random number in numpy
np.array([])

array([], dtype=float64)

In [48]:
np.random.random_sample((5, 5))

array([[0.37702792, 0.36022223, 0.81964291, 0.57958054, 0.74362389],
       [0.36384242, 0.82172138, 0.85198956, 0.52857549, 0.04384718],
       [0.08965347, 0.41454865, 0.63306633, 0.75783229, 0.51225449],
       [0.77298711, 0.33736537, 0.52873257, 0.89799161, 0.27091999],
       [0.75339941, 0.79382987, 0.2856516 , 0.82835513, 0.66847281]])

In [53]:
np.random.rand(4, 2)

array([[0.89785151, 0.07919847],
       [0.67994679, 0.47884615],
       [0.15315839, 0.3051873 ],
       [0.88246952, 0.7376239 ]])

In [55]:
np.random.randn()

2.1290543292986195

In [57]:
arr1 = np.zeros((2, 4), dtype=int)
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
arr1[arr1 > -1]

array([0, 0, 0, 0, 0, 0, 0, 0])