In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
np.random.seed(1)

In [4]:
X = 2*np.random.rand(100, 1)

In [5]:
X

array([[8.34044009e-01],
       [1.44064899e+00],
       [2.28749635e-04],
       [6.04665145e-01],
       [2.93511782e-01],
       [1.84677190e-01],
       [3.72520423e-01],
       [6.91121454e-01],
       [7.93534948e-01],
       [1.07763347e+00],
       [8.38389029e-01],
       [1.37043900e+00],
       [4.08904499e-01],
       [1.75623487e+00],
       [5.47751864e-02],
       [1.34093502e+00],
       [8.34609605e-01],
       [1.11737966e+00],
       [2.80773877e-01],
       [3.96202978e-01],
       [1.60148914e+00],
       [1.93652315e+00],
       [6.26848356e-01],
       [1.38464523e+00],
       [1.75277830e+00],
       [1.78921333e+00],
       [1.70088423e-01],
       [7.81095665e-02],
       [3.39660839e-01],
       [1.75628501e+00],
       [1.96693668e-01],
       [8.42215250e-01],
       [1.91577906e+00],
       [1.06633057e+00],
       [1.38375423e+00],
       [6.31031262e-01],
       [1.37300186e+00],
       [1.66925134e+00],
       [3.65765547e-02],
       [1.50028863e+00],


In [6]:
# generate random synthetic y
y = 4 + 3 * X + 1.5*X**2 + np.random.randn(100, 1)

In [7]:
y

array([[ 7.86121109],
       [ 9.41295   ],
       [ 3.69448231],
       [ 7.19039999],
       [ 5.23985383],
       [ 5.36720125],
       [ 5.10339032],
       [ 6.58907959],
       [ 7.51171281],
       [ 9.38489289],
       [ 7.76781105],
       [11.04748023],
       [ 4.80685555],
       [14.2728098 ],
       [ 4.29064731],
       [11.84944906],
       [ 8.74760648],
       [ 9.41010133],
       [ 4.58528764],
       [ 4.78534373],
       [13.07511295],
       [15.5120924 ],
       [ 6.12609969],
       [11.07339618],
       [13.24668175],
       [14.86759851],
       [ 4.10653181],
       [ 5.46798806],
       [ 5.59552839],
       [14.48923908],
       [ 3.55320176],
       [ 7.76001797],
       [15.99320774],
       [ 7.95088243],
       [10.75720782],
       [ 6.52300901],
       [ 9.57358939],
       [13.5025135 ],
       [ 4.95789708],
       [11.01764891],
       [16.15079003],
       [10.53522159],
       [ 6.11586144],
       [10.85767477],
       [ 5.8047074 ],
       [ 8

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [9]:
X_train.shape

(80, 1)

In [10]:
X_test.shape

(20, 1)

In [11]:
y_train.shape

(80, 1)

In [12]:
# perform polynomial regression
from sklearn.preprocessing import PolynomialFeatures

poly_features = PolynomialFeatures(degree=2, include_bias=False)

In [13]:
poly_features

,degree,2
,interaction_only,False
,include_bias,False
,order,'C'


In [15]:
X_poly_train = poly_features.fit_transform(X_train)

In [16]:
from sklearn.linear_model import LinearRegression

poly_reg = LinearRegression()

In [17]:
poly_reg.fit(X_poly_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [18]:
poly_reg.coef_

array([[2.19368573, 1.83687391]])

In [19]:
poly_reg.intercept_

array([4.37045389])