In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [5]:
from sklearn.datasets import load_iris
data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
X = data.data
y = data.target

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [10]:
from sklearn.preprocessing import StandardScaler # mean = 0, sigma = 1
scaler = StandardScaler()
X_train =scaler.fit_transform(X_train)

In [11]:
from sklearn.decomposition import PCA
pca = PCA()

In [12]:
pca

,n_components,None
,copy,True
,whiten,False
,svd_solver,'auto'
,tol,0.0
,iterated_power,'auto'
,n_oversamples,10
,power_iteration_normalizer,'auto'
,random_state,None


In [13]:
X_train = pca.fit_transform(X_train)
X_train

array([[ 3.29187211e+00, -1.64765395e-01,  7.27509357e-01,
        -5.78968617e-02],
       [-1.79681257e+00,  1.59337640e+00,  4.43385293e-01,
        -8.32121597e-02],
       [-2.30351105e+00,  8.69431210e-01,  2.33792304e-02,
         2.34275331e-02],
       [-2.02984587e+00, -5.59980278e-01,  3.92793836e-02,
        -1.38513261e-01],
       [ 9.09507841e-03, -9.68249823e-01, -5.55780350e-01,
         3.73471773e-02],
       [-2.09778967e+00,  4.52095658e-01,  1.94589630e-01,
        -1.74901668e-02],
       [-1.96393609e+00,  8.23951366e-01,  5.15626453e-01,
        -2.10836333e-01],
       [ 2.49741981e+00,  2.55439705e+00,  2.78249238e-01,
         2.39201187e-01],
       [ 1.87223188e+00,  6.45015818e-01,  7.34520648e-02,
        -2.04303483e-01],
       [ 2.31306020e+00,  3.19175762e-01,  6.91328103e-01,
         2.17802182e-01],
       [ 1.85690136e+00, -2.09457613e-01, -3.25721459e-01,
        -9.87875317e-02],
       [ 1.17626383e+00, -3.27992385e-01, -1.15904903e-01,
      

In [14]:
X_test = scaler.transform(X_test)

In [15]:
X_test = pca.fit_transform(X_test)

In [16]:
X_test

array([[-2.58987176,  1.29123251,  0.35336928, -0.14651026],
       [-0.09628312, -1.80670655, -0.06702152, -0.21496302],
       [ 0.76597301,  0.29430213,  0.39371538, -0.07327815],
       [-2.52097462,  0.88440723, -0.07397243, -0.1591697 ],
       [ 1.57512883,  2.95990453,  0.1659167 ,  0.26995568],
       [ 0.49922864,  0.75408928, -0.26170124,  0.09226241],
       [ 1.63301823,  0.90325067, -0.24828623, -0.4454381 ],
       [-2.37638622,  0.54108301, -0.30981163,  0.16354312],
       [-2.13759073, -0.95554442, -0.00643433,  0.10620785],
       [ 1.70907315,  1.14500173, -0.38463045, -0.14823359],
       [ 0.45124263, -0.9672683 , -0.09817805,  0.09953847],
       [-2.3951272 ,  0.91424046, -0.11691484,  0.01949229],
       [ 1.96811093,  0.85581638,  0.06405882, -0.03325801],
       [ 0.53436197,  0.58712169, -0.00514981,  0.01575371],
       [ 0.66331202, -0.25864575, -0.11383291,  0.04002761],
       [-2.38887525, -1.16899217, -0.21758373,  0.05614274],
       [ 0.5386756 , -1.

In [17]:
pca.components_

array([[ 0.43958974, -0.46988855,  0.56005943,  0.52182281],
       [ 0.53533601,  0.82125376,  0.13276696,  0.14604985],
       [ 0.68182032, -0.29986253, -0.1911068 , -0.63928218],
       [-0.23515373,  0.12177631,  0.79510035, -0.54560855]])

In [18]:
pca.explained_variance_ratio_

array([0.72653676, 0.24356295, 0.02310555, 0.00679474])