In [2]:
import torch

In [3]:
t1 = torch.tensor(4)
t1

tensor(4)

In [4]:
t1.dtype

torch.int64

In [5]:
torch.tensor([1, 2, 3, 4])

tensor([1, 2, 3, 4])

In [ ]:
torch.tensor([[1, 2, 3, 4]])

tensor([[1, 2, 3, 4]])

In [8]:
#create tensors


x = torch.tensor(3.)
w = torch.tensor(4. , requires_grad = True)
b = torch.tensor(5., requires_grad = True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [9]:
y = w*x + b

In [10]:
y

tensor(17., grad_fn=<AddBackward0>)

In [13]:
y.backward()

In [14]:
x.grad, w.grad, b.grad

(None, tensor(3.), tensor(1.))

In [16]:
t6 = torch.full((3, 5), 16)
t6

tensor([[16, 16, 16, 16, 16],
        [16, 16, 16, 16, 16],
        [16, 16, 16, 16, 16]])

In [17]:
t7 = torch.full((3, 5), 1)
t7

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [18]:
torch.cat((t6, t7))

tensor([[16, 16, 16, 16, 16],
        [16, 16, 16, 16, 16],
        [16, 16, 16, 16, 16],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1]])

In [19]:
t7.reshape(1, 3, 5)

tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]])