In [1]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("Device:", torch.cuda.get_device_name(0))
    x = torch.rand(5000, 5000).to("cuda")
    y = torch.rand(5000, 5000).to("cuda")
    z = torch.matmul(x, y)
    print("Computation done on:", z.device)


PyTorch version: 2.9.0+cu126
CUDA available: True
Device: NVIDIA GeForce RTX 2050
Computation done on: cuda:0


## Creating Tensor

In [12]:
# using empty
a = torch.empty(2, 4)
# check type
type(a)

torch.Tensor

In [13]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
# using ones
torch.ones(2, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [24]:
# using rand
torch.rand(2, 3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [21]:
# manual seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [23]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [25]:
# using torch.tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
# other ways

# arrange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [28]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Tensor Shapes

In [29]:
a.shape

torch.Size([2, 4])

In [30]:
torch.empty_like(x)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')

In [34]:
torch.zeros_like(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
torch.rand_like(a, dtype=torch.float)

tensor([[0.7118, 0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239, 0.3023]])

## Tensor Data Types

In [36]:
a.dtype

torch.float32

In [38]:
# assign data types
x = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

In [39]:
x.dtype

torch.int32

In [42]:
x = x.to(torch.float32)

In [43]:
x.dtype

torch.float32

## Mathematical Operations

### 1. Scalar Operations

In [49]:
print(x + 2)
print(x * 2)
print(x - 1)
print(x / 2)

tensor([3., 4., 5.])
tensor([2., 4., 6.])
tensor([0., 1., 2.])
tensor([0.5000, 1.0000, 1.5000])


In [69]:
a = torch.rand(3, 3)
b = torch.rand(3, 3)

In [55]:
a ** b

tensor([[0.2771, 0.9096, 0.8672],
        [0.9839, 0.6515, 0.9868]])

In [56]:
c = torch.tensor([1, -2, 3, -4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [58]:
torch.sum(torch.abs(c))

tensor(10)

In [63]:
torch.mean(c.to(torch.float), dim=0)

tensor(-0.5000)

In [64]:
torch.max(c)

tensor(3)

In [ ]:
torch.min(c)

tensor(-4)

In [67]:
c = c.to(torch.float)
torch.std(c)

tensor(3.1091)

In [70]:
torch.matmul(a, b)

tensor([[0.1718, 0.7503, 0.3003],
        [0.6733, 1.2841, 0.5414],
        [0.5537, 1.0411, 0.4048]])

In [71]:
torch.transpose(a, 0, 1)

tensor([[0.7909, 0.2209, 0.1629],
        [0.4235, 0.9535, 0.8902],
        [0.0169, 0.7064, 0.5163]])

In [73]:
torch.det(a)

tensor(-0.1069)

In [74]:
torch.inverse(a)

tensor([[ 1.2778,  1.9050, -2.6484],
        [-0.0095, -3.7949,  5.1927],
        [-0.3867,  5.9424, -6.1812]])

In [82]:
# log, exp, sqrt, sigmid, softmax, relu
torch.log(a)
torch.exp(a)
torch.sqrt(a)
torch.sigmoid(a)
# torch.softmax(a)
torch.relu(a)

tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064],
        [0.1629, 0.8902, 0.5163]])

In [89]:
id(a)

2366720809936

In [90]:
id(b)

2366720543872

In [85]:
a = b

In [88]:
a = b.clone()

In [91]:
device = torch.device('cuda')

In [92]:
torch.rand(2, 3, device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [93]:
a

tensor([[0.0359, 0.6476, 0.3430],
        [0.3182, 0.5261, 0.0447],
        [0.5123, 0.9051, 0.5989]])

In [97]:
import torch
import time

# Size of the matrices
N = 10000

# CPU tensors
a_cpu = torch.rand((N, N))
b_cpu = torch.rand((N, N))

# GPU tensors (if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
a_gpu = a_cpu.to(device)
b_gpu = b_cpu.to(device)

# CPU matmul timing
start = time.time()
c_cpu = torch.matmul(a_cpu, b_cpu)
cpu_time = time.time() - start
print(f"CPU matmul time: {cpu_time:.4f} seconds")

# GPU matmul timing
# Make sure to synchronize before and after timing
torch.cuda.synchronize()  # Wait for GPU
start = time.time()
c_gpu = torch.matmul(a_gpu, b_gpu)
torch.cuda.synchronize()  # Wait for GPU to finish
gpu_time = time.time() - start
print(f"GPU matmul time: {gpu_time:.4f} seconds")

# Optional: Verify results are close
print("Are results close?", torch.allclose(c_cpu, c_gpu.cpu(), atol=1e-6))


CPU matmul time: 5.8925 seconds
GPU matmul time: 0.6378 seconds
Are results close? True
