In [1]:
import torch
import torch.nn as nn

In [16]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()

        self.network = nn.Sequential(
          nn.Linear(num_features, 3),
          nn.ReLU(),
          nn.Linear(3, 1),
          nn.Sigmoid()
        )
        
    def forward(self, features):
        out = self.network(features)
        return out

In [11]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

# model.forward(features) 
model(features)

tensor([[0.4699],
        [0.4781],
        [0.4699],
        [0.4737],
        [0.4560],
        [0.4649],
        [0.4699],
        [0.4709],
        [0.4644],
        [0.4728]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear1.bias, model.linear1.weight

(Parameter containing:
 tensor([-0.1673,  0.4340,  0.1480], requires_grad=True),
 Parameter containing:
 tensor([[ 0.3732,  0.4322,  0.0047, -0.2384, -0.0846],
         [-0.2164, -0.2318, -0.3370, -0.3175, -0.2884],
         [-0.2063, -0.2468,  0.0273,  0.0527, -0.1085]], requires_grad=True))

In [14]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00